# 1. 강의영상 

# 2. Imports

In [3]:
import numpy as np
import pandas as pd
import sklearn.linear_model
import matplotlib.pyplot as plt

# 3. 개념

In [14]:
df = pd.read_csv('https://raw.githubusercontent.com/guebin/MP2023/main/posts/employment.csv')
df

toeic       gpa  employment
0      135  0.051535           0
1      935  0.355496           0
2      485  2.228435           0
3       65  1.179701           0
4      445  3.962356           1
..     ...       ...         ...
495    280  4.288465           1
496    310  2.601212           1
497    225  0.042323           0
498    320  1.041416           0
499    375  3.626883           1

[500 rows x 3 columns]

In [15]:
err = np.random.rand(500*50).reshape(500,50) - 0.5

In [16]:
df_extra = pd.DataFrame(df.toeic.to_numpy().reshape(500,1) + err,columns = ['toeic'+str(i) for i in range(50)])

In [17]:
df_extra

toeic0      toeic1      toeic2      toeic3      toeic4      toeic5  \
0    134.637404  134.810613  135.047559  135.230454  134.730604  135.125041   
1    935.054822  935.025802  935.383200  934.589168  935.184234  935.091992   
2    484.645276  484.608130  485.252176  485.226587  485.429446  484.981494   
3     65.080005   65.000145   64.656334   64.881600   65.026194   65.124617   
4    445.489457  444.921433  445.039217  445.392784  444.982201  444.693898   
..          ...         ...         ...         ...         ...         ...   
495  280.293134  280.165561  279.645811  280.196111  280.486494  279.652782   
496  309.944564  309.658356  309.875819  310.472151  310.346712  310.156749   
497  224.718679  224.666306  224.906828  224.605848  224.815449  224.670423   
498  320.498004  319.829881  320.123752  320.168471  319.531438  320.313713   
499  374.540043  375.032790  374.698081  374.831173  374.530273  375.248162   

         toeic6      toeic7      toeic8      toeic9  ...     toeic40  \
0    135.309595  134.541088  134.612264  134.729316  ...  135.020978   
1    935.181948  934.767556  934.533083  935.474649  ...  934.950770   
2    485.194748  485.118643  484.530357  485.035401  ...  484.801257   
3     65.430251   64.648263   65.421291   65.320809  ...   64.793013   
4    444.688475  444.757694  444.985930  444.556764  ...  444.842304   
..          ...         ...         ...         ...  ...         ...   
495  280.116807  279.639799  280.065961  280.300783  ...  280.279252   
496  310.065352  309.869189  310.470495  309.569062  ...  310.275754   
497  224.728347  225.307142  225.221862  225.288290  ...  224.609073   
498  319.568320  319.682671  319.724345  319.570206  ...  320.365921   
499  375.190112  375.108823  375.407518  374.794110  ...  375.055970   

        toeic41     toeic42     toeic43     toeic44     toeic45     toeic46  \
0    135.351798  134.506575  134.902801  135.313102  134.903651  134.859288   
1    934.872774  935.101053  935.289154  935.260573  934.917077  934.997652   
2    484.540547  485.015453  484.625987  485.240201  484.952549  485.205274   
3     65.333315   65.303294   64.762200   64.867230   64.516832   64.654206   
4    445.081586  445.312125  444.624320  445.490126  444.771435  444.992276   
..          ...         ...         ...         ...         ...         ...   
495  280.021474  279.736774  279.960022  279.746936  280.035774  280.116567   
496  309.730353  309.537577  309.673073  310.130752  310.250583  310.234853   
497  225.069245  224.641710  224.949189  225.352408  225.390987  224.612791   
498  320.338247  319.827729  319.927630  319.722164  320.143775  320.233901   
499  374.717735  375.069956  375.240235  374.825242  375.460675  374.959833   

        toeic47     toeic48     toeic49  
0    135.292753  135.112772  134.748709  
1    934.878607  935.466682  934.703981  
2    484.975447  484.749983  485.392396  
3     64.968567   64.765195   64.732883  
4    444.689208  445.328285  445.142289  
..          ...         ...         ...  
495  279.854080  279.885304  280.365986  
496  310.325332  310.018953  310.080176  
497  225.049095  224.717836  224.849184  
498  319.811682  319.503625  320.427865  
499  375.311423  375.498763  374.993965  

[500 rows x 50 columns]

In [18]:
df = pd.concat([df,df_extra],axis=1)

In [19]:
df

toeic       gpa  employment      toeic0      toeic1      toeic2  \
0      135  0.051535           0  134.637404  134.810613  135.047559   
1      935  0.355496           0  935.054822  935.025802  935.383200   
2      485  2.228435           0  484.645276  484.608130  485.252176   
3       65  1.179701           0   65.080005   65.000145   64.656334   
4      445  3.962356           1  445.489457  444.921433  445.039217   
..     ...       ...         ...         ...         ...         ...   
495    280  4.288465           1  280.293134  280.165561  279.645811   
496    310  2.601212           1  309.944564  309.658356  309.875819   
497    225  0.042323           0  224.718679  224.666306  224.906828   
498    320  1.041416           0  320.498004  319.829881  320.123752   
499    375  3.626883           1  374.540043  375.032790  374.698081   

         toeic3      toeic4      toeic5      toeic6  ...     toeic40  \
0    135.230454  134.730604  135.125041  135.309595  ...  135.020978   
1    934.589168  935.184234  935.091992  935.181948  ...  934.950770   
2    485.226587  485.429446  484.981494  485.194748  ...  484.801257   
3     64.881600   65.026194   65.124617   65.430251  ...   64.793013   
4    445.392784  444.982201  444.693898  444.688475  ...  444.842304   
..          ...         ...         ...         ...  ...         ...   
495  280.196111  280.486494  279.652782  280.116807  ...  280.279252   
496  310.472151  310.346712  310.156749  310.065352  ...  310.275754   
497  224.605848  224.815449  224.670423  224.728347  ...  224.609073   
498  320.168471  319.531438  320.313713  319.568320  ...  320.365921   
499  374.831173  374.530273  375.248162  375.190112  ...  375.055970   

        toeic41     toeic42     toeic43     toeic44     toeic45     toeic46  \
0    135.351798  134.506575  134.902801  135.313102  134.903651  134.859288   
1    934.872774  935.101053  935.289154  935.260573  934.917077  934.997652   
2    484.540547  485.015453  484.625987  485.240201  484.952549  485.205274   
3     65.333315   65.303294   64.762200   64.867230   64.516832   64.654206   
4    445.081586  445.312125  444.624320  445.490126  444.771435  444.992276   
..          ...         ...         ...         ...         ...         ...   
495  280.021474  279.736774  279.960022  279.746936  280.035774  280.116567   
496  309.730353  309.537577  309.673073  310.130752  310.250583  310.234853   
497  225.069245  224.641710  224.949189  225.352408  225.390987  224.612791   
498  320.338247  319.827729  319.927630  319.722164  320.143775  320.233901   
499  374.717735  375.069956  375.240235  374.825242  375.460675  374.959833   

        toeic47     toeic48     toeic49  
0    135.292753  135.112772  134.748709  
1    934.878607  935.466682  934.703981  
2    484.975447  484.749983  485.392396  
3     64.968567   64.765195   64.732883  
4    444.689208  445.328285  445.142289  
..          ...         ...         ...  
495  279.854080  279.885304  280.365986  
496  310.325332  310.018953  310.080176  
497  225.049095  224.717836  224.849184  
498  319.811682  319.503625  320.427865  
499  375.311423  375.498763  374.993965  

[500 rows x 53 columns]

In [23]:
df.to_csv("employment_manytoeic.csv",index=False)

In [20]:
df['employment'] = df['toeic'] * 1/200 + df['gpa']*1.3 + np.random.randn(500)

In [21]:
df_train, df_test = sklearn.model_selection.train_test_split(df,test_size=0.3)

In [8]:
X = df_train.drop(['employment'],axis=1)
y = df_train[['employment']]
XX = df_test.drop(['employment'],axis=1)
yy = df_test[['employment']]

In [9]:
predictr = sklearn.linear_model.LinearRegression()

In [10]:
predictr.fit(X,y)

LinearRegression()

In [11]:
predictr.coef_,predictr.intercept_

(array([[ 0.12873227,  1.36843626,  0.01267637,  0.25333314,  0.07580887,
          0.16951266,  0.17165306,  0.23475856, -0.24761195,  0.28310765,
         -0.16843361,  0.05744777, -0.08067886, -0.11577643, -0.00330179,
          0.06918065, -0.1207914 , -0.3211608 , -0.20182045, -0.0856689 ,
         -0.06999547,  0.1421365 ,  0.30169456, -0.1815216 ,  0.0368099 ,
          0.28667021,  0.18546914, -0.26762969, -0.06642038,  0.13174395,
         -0.2662439 , -0.11573981,  0.06994722,  0.3482305 ,  0.38400381,
         -0.15481502,  0.34253802,  0.09735465, -0.35596438, -0.08315674,
          0.00359051, -0.08655258, -0.1992766 , -0.29606932,  0.10050176,
          0.00952553, -0.20305699,  0.03498006, -0.32748608, -0.25911595,
         -0.00623853,  0.35836285]]),
 array([-0.28516272]))

In [12]:
predictr.score(X,y)

0.8565445058584887

In [13]:
predictr.score(XX,yy)

0.7856940428251548

In [14]:
X = df_train[['toeic','gpa']]
y = df_train[['employment']]
XX = df_test[['toeic','gpa']]
yy = df_test[['employment']]

In [15]:
predictr = sklearn.linear_model.LinearRegression()

In [16]:
predictr.fit(X,y)

LinearRegression()

In [17]:
predictr.coef_,predictr.intercept_

(array([[0.00531095, 1.36939247]]), array([-0.33612579]))

In [18]:
predictr.score(X,y)

0.8329365926760117

In [19]:
predictr.score(XX,yy)

0.8312893241857904

---

In [20]:
X = df_train.drop(['employment'],axis=1)
y = df_train[['employment']]
XX = df_test.drop(['employment'],axis=1)
yy = df_test[['employment']]

In [21]:
predictr = sklearn.linear_model.LassoCV(max_iter=500000)

In [22]:
predictr.fit(X,y)

/home/cgb2/anaconda3/envs/ag/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:1563: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LassoCV(max_iter=500000)

In [23]:
predictr.coef_

array([5.16661401e-03, 1.15051137e+00, 1.16072961e-04, 8.98586766e-07,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.99521456e-08, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 5.54603718e-07, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [24]:
predictr.score(X,y)

0.8196658131746754

In [25]:
predictr.score(XX,yy)

0.8092237908580237