# 1. 강의영상 

# 2. Imports

In [4]:
import numpy as np
import pandas as pd
import sklearn.linear_model

# 3. 상상

`-` 아래와 같은 가짜뉴스를 읽어보자.^[제가 ChatGPT를 이용하여 생성한 가짜뉴스입니다. 뉴스는 실제사실을 반영한 것이 아닙니다.]

**헤드라인**: "텝스와 다른 영어 인증 시험들, 결국은 토익과 비슷한 결과를 보여준다?"

---

**본문**:

최근 몇 년 동안, 토익의 신뢰성에 대한 논란이 계속되어 왔습니다. 이러한 배경 속에서 텝스(TEPS), 토플(TOEFL) 등 여러 새로운 영어 능력 평가 시험이 등장하였습니다. 많은 학생들과 직장인들은 이러한 새로운 시험들이 토익보다 더 신뢰성 있고 현실적인 능력을 평가할 것이라는 기대감을 가지고 있었습니다.

그러나 최근에 발표된 연구결과에 따르면, 텝스와 다른 영어 인증 시험들도 결국에는 토익과 매우 비슷한 성적 분포와 결과를 보여주었다고 합니다. 연구 팀은 여러 시험들간의 점수 분포와 성적의 상관관계를 분석한 결과, 대부분의 시험들이 실제 영어 능력에 대해 유사한 평가를 제공한다는 결론을 내렸습니다.

"많은 사람들이 새로운 시험들이 더 현실적이거나 다양한 영어 능력을 평가할 것이라 기대했지만, 실제로는 모든 시험들이 비슷한 결과를 보여주었습니다." 라며 연구 팀의 대표는 이렇게 언급하였습니다.

이러한 연구결과는 영어 능력 평가 시험의 표준화와 신뢰성에 대한 논의를 새롭게 불러일으킬 것으로 보입니다.


`-` 이 뉴스에 근거하여 아래의 가짜자료를 생성했다. 

In [95]:
df = pd.read_csv("https://raw.githubusercontent.com/guebin/MP2023/main/posts/employment_manytoeic.csv")
df.loc[:,['employment_score','gpa','toeic']]

employment_score       gpa  toeic
0           -0.949314  0.051535    135
1            4.861725  0.355496    935
2            5.582663  2.228435    485
3            3.919694  1.179701     65
4            8.286851  3.962356    445
..                ...       ...    ...
495          7.002081  4.288465    280
496          5.431050  2.601212    310
497          0.088812  0.042323    225
498          3.806388  1.041416    320
499          6.739095  3.626883    375

[500 rows x 3 columns]

In [109]:
df1 = df.loc[:,['employment_score','gpa','toeic']]
df2 = pd.DataFrame(np.random.randn(500*500).reshape(500,500)+df.toeic.to_numpy().reshape(-1,1),columns=['toeic'+str(i) for i in range(500)])
df = pd.concat([df1,df2],axis=1)

In [111]:
df.to_csv("employment_manytoeic.csv",index=False)

- toeic0,toeic1,... 등은 토익과 유사한 새로운 시험들을 의미함. (실제 점수는 정수이겠지만 편의상 소수점으로 사용하였음)
- employmet_score는 회사에 내부적으로 정의된 채점기준표이며, 이 기준표에 의하여 일정점수 이상인 사람은 합격하고, 그렇지 않은 사람은 불합격한다고 가정함. 


`-` 비밀: 사실 저는 데이터를 아래의 공식에 따라서 만들었어요..

```
employment_score = toeic*1/200 + gpa*1.3 + random 
````

# 4. 잘못된 분석 

In [85]:
df_train, df_test = sklearn.model_selection.train_test_split(df,test_size=0.3)

In [104]:
X = df_train.drop(['employment_score'],axis=1)
y = df_train[['employment_score']]
XX = df_test.drop(['employment_score'],axis=1)
yy = df_test[['employment_score']]

In [105]:
predictr = sklearn.linear_model.LinearRegression()

In [107]:
X.shape

(700, 502)

In [106]:
predictr.fit(X,y)

TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.

In [45]:
predictr.coef_,predictr.intercept_

(array([[ 1.14400698e+00,  5.21525186e-03,  3.49146846e-02,
          7.60918113e-02, -5.89282184e-02,  4.55418607e-02,
         -1.87471852e-02,  1.79975028e-02, -2.49407582e-02,
         -6.69333630e-02, -1.14014570e-01, -1.36132121e-02,
         -1.05102704e-01,  5.13661681e-02, -1.38518299e-01,
          9.03561040e-02,  2.83255586e-02,  7.50026577e-02,
          6.15970126e-02,  1.18137567e-01, -2.43042828e-02,
         -2.45790398e-02,  7.80819751e-02,  7.45585266e-02,
          5.70549334e-02, -8.52388264e-02, -1.96992967e-02,
          1.33784877e-01,  6.82701818e-02,  7.34029220e-02,
         -1.13025647e-01, -4.87166384e-02,  1.16105129e-01,
          2.63940271e-03, -2.91726960e-02,  4.42066771e-02,
         -6.14695304e-03,  2.51779972e-02,  6.39947852e-02,
         -2.27163688e-02, -7.21393826e-03, -6.17995311e-02,
          2.23961380e-03, -1.10092675e-01, -1.07429192e-01,
         -4.87051996e-02,  1.22589262e-01, -7.52840784e-02,
         -2.00123139e-02, -5.94992661e-0

- 실제계수값은 `토익*0.005`, `GPA*1.3` 인데.. GPA는 얼추맞는거 같지만, 토익은 딱봐도 틀려보임..

In [49]:
predictr.coef_

array([[ 1.14400698e+00,  5.21525186e-03,  3.49146846e-02,
         7.60918113e-02, -5.89282184e-02,  4.55418607e-02,
        -1.87471852e-02,  1.79975028e-02, -2.49407582e-02,
        -6.69333630e-02, -1.14014570e-01, -1.36132121e-02,
        -1.05102704e-01,  5.13661681e-02, -1.38518299e-01,
         9.03561040e-02,  2.83255586e-02,  7.50026577e-02,
         6.15970126e-02,  1.18137567e-01, -2.43042828e-02,
        -2.45790398e-02,  7.80819751e-02,  7.45585266e-02,
         5.70549334e-02, -8.52388264e-02, -1.96992967e-02,
         1.33784877e-01,  6.82701818e-02,  7.34029220e-02,
        -1.13025647e-01, -4.87166384e-02,  1.16105129e-01,
         2.63940271e-03, -2.91726960e-02,  4.42066771e-02,
        -6.14695304e-03,  2.51779972e-02,  6.39947852e-02,
        -2.27163688e-02, -7.21393826e-03, -6.17995311e-02,
         2.23961380e-03, -1.10092675e-01, -1.07429192e-01,
        -4.87051996e-02,  1.22589262e-01, -7.52840784e-02,
        -2.00123139e-02, -5.94992661e-02,  9.11406155e-0

In [50]:
predictr.score(X,y)

1.0

In [51]:
predictr.score(XX,yy)

0.4110927775350669

# 5. 제대로 분석했다면? 

## A. `toeic`과 `gpa`가 유의미한 변수라는걸 눈치챘다면? 

In [52]:
X = df_train[['toeic','gpa']]
y = df_train[['employment_score']]
XX = df_test[['toeic','gpa']]
yy = df_test[['employment_score']]

In [53]:
predictr = sklearn.linear_model.LinearRegression()

In [54]:
predictr.fit(X,y)

LinearRegression()

In [55]:
predictr.coef_,predictr.intercept_

(array([[0.00533198, 1.34477959]]), array([-0.22146319]))

In [56]:
predictr.score(X,y)

0.8437960436355036

In [57]:
predictr.score(XX,yy)

0.7915485480595327

## B. 하다못해 `toeic0`과 `gpa`로 적합했다면? 

In [77]:
X = df_train[['toeic0','gpa']]
y = df_train[['employment_score']]
XX = df_test[['toeic0','gpa']]
yy = df_test[['employment_score']]

In [72]:
predictr = sklearn.linear_model.LinearRegression()

In [73]:
predictr.fit(X,y)

LinearRegression()

In [74]:
predictr.coef_,predictr.intercept_

(array([[0.04682314, 1.33467026]]), array([-41.28978356]))

In [75]:
predictr.score(X,y)

0.48933221912961256

In [76]:
predictr.score(XX,yy)

0.43123395801472464

# 6. Discussions

`-` 어렴풋한 감각: 쓸모없는 변수가 많이 있으면 오히려 모형의 적합도가 떨어진다. (규칙을 찾으면 안될것에서 규칙을 찾고있으니까 잘 될리가 없지)

`-` 쓸모없는 변수란 느낌이 드는 경우?

- 경우1: 진짜 쓸모 없는거.. (X1= 부먹/찍먹, X2= 민초/민초X) $\to$ 애초에 `X1`,`X2`을 보고 `y`를 맞출 생각이 들지 않어.. 
- 경우2: 실제론 쓸모 있는데, 대체자가 있는 경우. (X1= toeic, X2= 유사toeic) $\to$ `X1` 을 보고 `y`를 맞출 것 같은 생각이 들어, 그리고 `X2`를 보고 `y`를 맞출 것 같은 생각도 들어. 그런데 `X1`이랑 `X2`는 너무 비슷해

`-` 경우1, 경우2 모두 과대적합(overfitting)을 야기한다. 그리고 경우2와 같은 상황에서 발생하는 문제를 특별히 다중공선성이라고 칭한다. 


`-` 다중공선성이 발생했을 경우 나타나는 특징

1. 계수들의 추정값이 불안정하다^[사실 `toeic의 계수 + toeic0의 계수 + ... + toeic49의 계수` $\approx$ `0.05` 이면 거진 올바른 추정아니야? 애초에 답이 여러개야]
2. 과대적합 문제를 불러올 수 있음 
3. 계수의 해석이 어려움

`-` 의문: 그래서 해결방법은? 변수를 잘 보고 제거하라고??